// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/coordinator/v1/coordinator.proto

package coordinatorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinatorService_RegisterNode_FullMethodName      = "/coordinator.v1.CoordinatorService/RegisterNode"
	CoordinatorService_Heartbeat_FullMethodName         = "/coordinator.v1.CoordinatorService/Heartbeat"
	CoordinatorService_DeregisterNode_FullMethodName    = "/coordinator.v1.CoordinatorService/DeregisterNode"
	CoordinatorService_StreamTasks_FullMethodName       = "/coordinator.v1.CoordinatorService/StreamTasks"
	CoordinatorService_SubmitTaskResult_FullMethodName  = "/coordinator.v1.CoordinatorService/SubmitTaskResult"
	CoordinatorService_GetCurrentModel_FullMethodName   = "/coordinator.v1.CoordinatorService/GetCurrentModel"
	CoordinatorService_ListModelVersions_FullMethodName = "/coordinator.v1.CoordinatorService/ListModelVersions"
	CoordinatorService_GetStakeStatus_FullMethodName    = "/coordinator.v1.CoordinatorService/GetStakeStatus"
	CoordinatorService_SubmitGradient_FullMethodName    = "/coordinator.v1.CoordinatorService/SubmitGradient"
)

// CoordinatorServiceClient is the client API for CoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─────────────────────────────────────────────
// CoordinatorService — primary node interface
// ─────────────────────────────────────────────
type CoordinatorServiceClient interface {
	// Node lifecycle
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	DeregisterNode(ctx context.Context, in *DeregisterNodeRequest, opts ...grpc.CallOption) (*DeregisterNodeResponse, error)
	// Task streaming — node opens a persistent stream to receive tasks
	StreamTasks(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Task], error)
	SubmitTaskResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*TaskResultAck, error)
	// Model versioning
	GetCurrentModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*ModelVersion, error)
	ListModelVersions(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// Node-facing stake info
	GetStakeStatus(ctx context.Context, in *GetStakeRequest, opts ...grpc.CallOption) (*StakeStatus, error)
	// FL participation
	SubmitGradient(ctx context.Context, in *GradientUpdate, opts ...grpc.CallOption) (*GradientAck, error)
}

type coordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceClient(cc grpc.ClientConnInterface) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) DeregisterNode(ctx context.Context, in *DeregisterNodeRequest, opts ...grpc.CallOption) (*DeregisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterNodeResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_DeregisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) StreamTasks(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Task], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoordinatorService_ServiceDesc.Streams[0], CoordinatorService_StreamTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, Task]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_StreamTasksClient = grpc.ServerStreamingClient[Task]

func (c *coordinatorServiceClient) SubmitTaskResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*TaskResultAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResultAck)
	err := c.cc.Invoke(ctx, CoordinatorService_SubmitTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) GetCurrentModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*ModelVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelVersion)
	err := c.cc.Invoke(ctx, CoordinatorService_GetCurrentModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ListModelVersions(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_ListModelVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) GetStakeStatus(ctx context.Context, in *GetStakeRequest, opts ...grpc.CallOption) (*StakeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StakeStatus)
	err := c.cc.Invoke(ctx, CoordinatorService_GetStakeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) SubmitGradient(ctx context.Context, in *GradientUpdate, opts ...grpc.CallOption) (*GradientAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradientAck)
	err := c.cc.Invoke(ctx, CoordinatorService_SubmitGradient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServiceServer is the server API for CoordinatorService service.
// All implementations must embed UnimplementedCoordinatorServiceServer
// for forward compatibility.
//
// ─────────────────────────────────────────────
// CoordinatorService — primary node interface
// ─────────────────────────────────────────────
type CoordinatorServiceServer interface {
	// Node lifecycle
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	DeregisterNode(context.Context, *DeregisterNodeRequest) (*DeregisterNodeResponse, error)
	// Task streaming — node opens a persistent stream to receive tasks
	StreamTasks(*HeartbeatRequest, grpc.ServerStreamingServer[Task]) error
	SubmitTaskResult(context.Context, *TaskResult) (*TaskResultAck, error)
	// Model versioning
	GetCurrentModel(context.Context, *GetModelRequest) (*ModelVersion, error)
	ListModelVersions(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// Node-facing stake info
	GetStakeStatus(context.Context, *GetStakeRequest) (*StakeStatus, error)
	// FL participation
	SubmitGradient(context.Context, *GradientUpdate) (*GradientAck, error)
	mustEmbedUnimplementedCoordinatorServiceServer()
}

// UnimplementedCoordinatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServiceServer struct{}

func (UnimplementedCoordinatorServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedCoordinatorServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCoordinatorServiceServer) DeregisterNode(context.Context, *DeregisterNodeRequest) (*DeregisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterNode not implemented")
}
func (UnimplementedCoordinatorServiceServer) StreamTasks(*HeartbeatRequest, grpc.ServerStreamingServer[Task]) error {
	return status.Error(codes.Unimplemented, "method StreamTasks not implemented")
}
func (UnimplementedCoordinatorServiceServer) SubmitTaskResult(context.Context, *TaskResult) (*TaskResultAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTaskResult not implemented")
}
func (UnimplementedCoordinatorServiceServer) GetCurrentModel(context.Context, *GetModelRequest) (*ModelVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentModel not implemented")
}
func (UnimplementedCoordinatorServiceServer) ListModelVersions(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModelVersions not implemented")
}
func (UnimplementedCoordinatorServiceServer) GetStakeStatus(context.Context, *GetStakeRequest) (*StakeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStakeStatus not implemented")
}
func (UnimplementedCoordinatorServiceServer) SubmitGradient(context.Context, *GradientUpdate) (*GradientAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitGradient not implemented")
}
func (UnimplementedCoordinatorServiceServer) mustEmbedUnimplementedCoordinatorServiceServer() {}
func (UnimplementedCoordinatorServiceServer) testEmbeddedByValue()                            {}

// UnsafeCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceServer will
// result in compilation errors.
type UnsafeCoordinatorServiceServer interface {
	mustEmbedUnimplementedCoordinatorServiceServer()
}

func RegisterCoordinatorServiceServer(s grpc.ServiceRegistrar, srv CoordinatorServiceServer) {
	// If the following call panics, it indicates UnimplementedCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorService_ServiceDesc, srv)
}

func _CoordinatorService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_DeregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).DeregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_DeregisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).DeregisterNode(ctx, req.(*DeregisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_StreamTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HeartbeatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoordinatorServiceServer).StreamTasks(m, &grpc.GenericServerStream[HeartbeatRequest, Task]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_StreamTasksServer = grpc.ServerStreamingServer[Task]

func _CoordinatorService_SubmitTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).SubmitTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_SubmitTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).SubmitTaskResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_GetCurrentModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).GetCurrentModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_GetCurrentModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).GetCurrentModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ListModelVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ListModelVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ListModelVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ListModelVersions(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_GetStakeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).GetStakeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_GetStakeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).GetStakeStatus(ctx, req.(*GetStakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_SubmitGradient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradientUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).SubmitGradient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_SubmitGradient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).SubmitGradient(ctx, req.(*GradientUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorService_ServiceDesc is the grpc.ServiceDesc for CoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordinator.v1.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _CoordinatorService_RegisterNode_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CoordinatorService_Heartbeat_Handler,
		},
		{
			MethodName: "DeregisterNode",
			Handler:    _CoordinatorService_DeregisterNode_Handler,
		},
		{
			MethodName: "SubmitTaskResult",
			Handler:    _CoordinatorService_SubmitTaskResult_Handler,
		},
		{
			MethodName: "GetCurrentModel",
			Handler:    _CoordinatorService_GetCurrentModel_Handler,
		},
		{
			MethodName: "ListModelVersions",
			Handler:    _CoordinatorService_ListModelVersions_Handler,
		},
		{
			MethodName: "GetStakeStatus",
			Handler:    _CoordinatorService_GetStakeStatus_Handler,
		},
		{
			MethodName: "SubmitGradient",
			Handler:    _CoordinatorService_SubmitGradient_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTasks",
			Handler:       _CoordinatorService_StreamTasks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/coordinator/v1/coordinator.proto",
}
