// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/coordinator/v1/coordinator.proto

package coordinatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─────────────────────────────────────────────
// Registration
// ─────────────────────────────────────────────
type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`   // Ed25519 hex
	LnNodeUri     string                 `protobuf:"bytes,2,opt,name=ln_node_uri,json=lnNodeUri,proto3" json:"ln_node_uri,omitempty"` // pubkey@host:port (clearnet or .onion)
	Capabilities  *NodeCapabilities      `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                           // Ed25519 sig over canonical fields
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // Unix seconds (anti-replay)
	OnionAddress  string                 `protobuf:"bytes,6,opt,name=onion_address,json=onionAddress,proto3" json:"onion_address,omitempty"` // optional Tor v3 .onion hostname for control-plane access
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterNodeRequest) GetLnNodeUri() string {
	if x != nil {
		return x.LnNodeUri
	}
	return ""
}

func (x *RegisterNodeRequest) GetCapabilities() *NodeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterNodeRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RegisterNodeRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RegisterNodeRequest) GetOnionAddress() string {
	if x != nil {
		return x.OnionAddress
	}
	return ""
}

type NodeCapabilities struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Tier               string                 `protobuf:"bytes,1,opt,name=tier,proto3" json:"tier,omitempty"` // "t1" | "t2" | "t3"
	VramGb             float32                `protobuf:"fixed32,2,opt,name=vram_gb,json=vramGb,proto3" json:"vram_gb,omitempty"`
	RamGb              float32                `protobuf:"fixed32,3,opt,name=ram_gb,json=ramGb,proto3" json:"ram_gb,omitempty"`
	BandwidthMbps      float32                `protobuf:"fixed32,4,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"`
	SupportedTaskTypes []string               `protobuf:"bytes,5,rep,name=supported_task_types,json=supportedTaskTypes,proto3" json:"supported_task_types,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeCapabilities) Reset() {
	*x = NodeCapabilities{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapabilities) ProtoMessage() {}

func (x *NodeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapabilities.ProtoReflect.Descriptor instead.
func (*NodeCapabilities) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *NodeCapabilities) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *NodeCapabilities) GetVramGb() float32 {
	if x != nil {
		return x.VramGb
	}
	return 0
}

func (x *NodeCapabilities) GetRamGb() float32 {
	if x != nil {
		return x.RamGb
	}
	return 0
}

func (x *NodeCapabilities) GetBandwidthMbps() float32 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *NodeCapabilities) GetSupportedTaskTypes() []string {
	if x != nil {
		return x.SupportedTaskTypes
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                          // "active" | "pending"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                        // human-readable; includes channel instructions if pending
	StakeSats     int64                  `protobuf:"varint,4,opt,name=stake_sats,json=stakeSats,proto3" json:"stake_sats,omitempty"`  // current locked sats (0 if pending)
	BonusMult     float32                `protobuf:"fixed32,5,opt,name=bonus_mult,json=bonusMult,proto3" json:"bonus_mult,omitempty"` // current stake bonus multiplier
	ErrorCode     string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`   // "INSUFFICIENT_STAKE" | "" on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNodeResponse) GetStakeSats() int64 {
	if x != nil {
		return x.StakeSats
	}
	return 0
}

func (x *RegisterNodeResponse) GetBonusMult() float32 {
	if x != nil {
		return x.BonusMult
	}
	return 0
}

func (x *RegisterNodeResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// ─────────────────────────────────────────────
// Heartbeat
// ─────────────────────────────────────────────
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // sig over (node_id + timestamp)
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       *NodeMetrics           `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetMetrics() *NodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type NodeMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GpuUtilizationPct float32                `protobuf:"fixed32,1,opt,name=gpu_utilization_pct,json=gpuUtilizationPct,proto3" json:"gpu_utilization_pct,omitempty"`
	VramUsedGb        float32                `protobuf:"fixed32,2,opt,name=vram_used_gb,json=vramUsedGb,proto3" json:"vram_used_gb,omitempty"`
	ActiveTasks       int32                  `protobuf:"varint,3,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	UptimeHours       float32                `protobuf:"fixed32,4,opt,name=uptime_hours,json=uptimeHours,proto3" json:"uptime_hours,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *NodeMetrics) GetGpuUtilizationPct() float32 {
	if x != nil {
		return x.GpuUtilizationPct
	}
	return 0
}

func (x *NodeMetrics) GetVramUsedGb() float32 {
	if x != nil {
		return x.VramUsedGb
	}
	return 0
}

func (x *NodeMetrics) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *NodeMetrics) GetUptimeHours() float32 {
	if x != nil {
		return x.UptimeHours
	}
	return 0
}

type HeartbeatResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PendingTasks       int32                  `protobuf:"varint,1,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	CoordinatorVersion string                 `protobuf:"bytes,2,opt,name=coordinator_version,json=coordinatorVersion,proto3" json:"coordinator_version,omitempty"`
	UpdateAvailable    bool                   `protobuf:"varint,3,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"` // new model checkpoint available
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetPendingTasks() int32 {
	if x != nil {
		return x.PendingTasks
	}
	return 0
}

func (x *HeartbeatResponse) GetCoordinatorVersion() string {
	if x != nil {
		return x.CoordinatorVersion
	}
	return ""
}

func (x *HeartbeatResponse) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

// ─────────────────────────────────────────────
// Deregistration
// ─────────────────────────────────────────────
type DeregisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // "shutdown" | "maintenance" | etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterNodeRequest) Reset() {
	*x = DeregisterNodeRequest{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterNodeRequest) ProtoMessage() {}

func (x *DeregisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterNodeRequest.ProtoReflect.Descriptor instead.
func (*DeregisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *DeregisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeregisterNodeRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *DeregisterNodeRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeregisterNodeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeregisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterNodeResponse) Reset() {
	*x = DeregisterNodeResponse{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterNodeResponse) ProtoMessage() {}

func (x *DeregisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterNodeResponse.ProtoReflect.Descriptor instead.
func (*DeregisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *DeregisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeregisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ─────────────────────────────────────────────
// Tasks
// ─────────────────────────────────────────────
type Task struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType         string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`                         // "inference" | "fl_round" | "gradient_agg" | "audit_repo" | "embed_data"
	EncryptedPayload []byte                 `protobuf:"bytes,3,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"` // NaCl box encrypted to node's pubkey
	TimeoutSeconds   int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RewardSats       int64                  `protobuf:"varint,5,opt,name=reward_sats,json=rewardSats,proto3" json:"reward_sats,omitempty"`
	ModelVersion     string                 `protobuf:"bytes,6,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`       // required model version
	CoordinatorSig   []byte                 `protobuf:"bytes,7,opt,name=coordinator_sig,json=coordinatorSig,proto3" json:"coordinator_sig,omitempty"` // sig over task_id + payload_hash
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *Task) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *Task) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Task) GetRewardSats() int64 {
	if x != nil {
		return x.RewardSats
	}
	return 0
}

func (x *Task) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *Task) GetCoordinatorSig() []byte {
	if x != nil {
		return x.CoordinatorSig
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	OutputHash    []byte                 `protobuf:"bytes,3,opt,name=output_hash,json=outputHash,proto3" json:"output_hash,omitempty"` // SHA-256 of output
	Output        []byte                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`                           // task output (gradient delta, inference result, etc.)
	ExecMs        int64                  `protobuf:"varint,5,opt,name=exec_ms,json=execMs,proto3" json:"exec_ms,omitempty"`
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 sig over (task_id + output_hash)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TaskResult) GetOutputHash() []byte {
	if x != nil {
		return x.OutputHash
	}
	return nil
}

func (x *TaskResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *TaskResult) GetExecMs() int64 {
	if x != nil {
		return x.ExecMs
	}
	return 0
}

func (x *TaskResult) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TaskResultAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectionReason string                 `protobuf:"bytes,2,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"` // "" on success
	PaymentStatus   string                 `protobuf:"bytes,3,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`       // "dispatched" | "pending" | "failed"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskResultAck) Reset() {
	*x = TaskResultAck{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultAck) ProtoMessage() {}

func (x *TaskResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultAck.ProtoReflect.Descriptor instead.
func (*TaskResultAck) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *TaskResultAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TaskResultAck) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *TaskResultAck) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

// ─────────────────────────────────────────────
// Model versioning
// ─────────────────────────────────────────────
type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubModelId    string                 `protobuf:"bytes,1,opt,name=sub_model_id,json=subModelId,proto3" json:"sub_model_id,omitempty"` // "" = all sub-models
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *GetModelRequest) GetSubModelId() string {
	if x != nil {
		return x.SubModelId
	}
	return ""
}

type ModelVersion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VersionId      string                 `protobuf:"bytes,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	RoundNumber    int32                  `protobuf:"varint,2,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                                                           // Unix seconds
	SubModelHashes map[string]string      `protobuf:"bytes,4,rep,name=sub_model_hashes,json=subModelHashes,proto3" json:"sub_model_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // sub_model_id → SHA-256
	OtsProofUrls   map[string]string      `protobuf:"bytes,5,rep,name=ots_proof_urls,json=otsProofUrls,proto3" json:"ots_proof_urls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // sub_model_id → URL
	BtcBlock       int32                  `protobuf:"varint,6,opt,name=btc_block,json=btcBlock,proto3" json:"btc_block,omitempty"`                                                                                              // 0 if OTS pending
	OtsVerified    bool                   `protobuf:"varint,7,opt,name=ots_verified,json=otsVerified,proto3" json:"ots_verified,omitempty"`
	CoordinatorSig string                 `protobuf:"bytes,8,opt,name=coordinator_sig,json=coordinatorSig,proto3" json:"coordinator_sig,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModelVersion) Reset() {
	*x = ModelVersion{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelVersion) ProtoMessage() {}

func (x *ModelVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelVersion.ProtoReflect.Descriptor instead.
func (*ModelVersion) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{12}
}

func (x *ModelVersion) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *ModelVersion) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *ModelVersion) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelVersion) GetSubModelHashes() map[string]string {
	if x != nil {
		return x.SubModelHashes
	}
	return nil
}

func (x *ModelVersion) GetOtsProofUrls() map[string]string {
	if x != nil {
		return x.OtsProofUrls
	}
	return nil
}

func (x *ModelVersion) GetBtcBlock() int32 {
	if x != nil {
		return x.BtcBlock
	}
	return 0
}

func (x *ModelVersion) GetOtsVerified() bool {
	if x != nil {
		return x.OtsVerified
	}
	return false
}

func (x *ModelVersion) GetCoordinatorSig() string {
	if x != nil {
		return x.CoordinatorSig
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{13}
}

func (x *ListModelsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListModelsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*ModelVersion        `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{14}
}

func (x *ListModelsResponse) GetVersions() []*ModelVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListModelsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ─────────────────────────────────────────────
// Stake
// ─────────────────────────────────────────────
type GetStakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStakeRequest) Reset() {
	*x = GetStakeRequest{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStakeRequest) ProtoMessage() {}

func (x *GetStakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStakeRequest.ProtoReflect.Descriptor instead.
func (*GetStakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{15}
}

func (x *GetStakeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type StakeStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChannelId       string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	CapacitySats    int64                  `protobuf:"varint,2,opt,name=capacity_sats,json=capacitySats,proto3" json:"capacity_sats,omitempty"`
	LocalBalance    int64                  `protobuf:"varint,3,opt,name=local_balance,json=localBalance,proto3" json:"local_balance,omitempty"`
	TierMinimum     int64                  `protobuf:"varint,4,opt,name=tier_minimum,json=tierMinimum,proto3" json:"tier_minimum,omitempty"`
	BonusMultiplier float32                `protobuf:"fixed32,5,opt,name=bonus_multiplier,json=bonusMultiplier,proto3" json:"bonus_multiplier,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                          // "active" | "degraded" | "force_closed"
	LastVerifiedAt  int64                  `protobuf:"varint,7,opt,name=last_verified_at,json=lastVerifiedAt,proto3" json:"last_verified_at,omitempty"` // Unix seconds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StakeStatus) Reset() {
	*x = StakeStatus{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakeStatus) ProtoMessage() {}

func (x *StakeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakeStatus.ProtoReflect.Descriptor instead.
func (*StakeStatus) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{16}
}

func (x *StakeStatus) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *StakeStatus) GetCapacitySats() int64 {
	if x != nil {
		return x.CapacitySats
	}
	return 0
}

func (x *StakeStatus) GetLocalBalance() int64 {
	if x != nil {
		return x.LocalBalance
	}
	return 0
}

func (x *StakeStatus) GetTierMinimum() int64 {
	if x != nil {
		return x.TierMinimum
	}
	return 0
}

func (x *StakeStatus) GetBonusMultiplier() float32 {
	if x != nil {
		return x.BonusMultiplier
	}
	return 0
}

func (x *StakeStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StakeStatus) GetLastVerifiedAt() int64 {
	if x != nil {
		return x.LastVerifiedAt
	}
	return 0
}

// ─────────────────────────────────────────────
// Federated learning
// ─────────────────────────────────────────────
type GradientUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RoundNumber   int32                  `protobuf:"varint,2,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	GradientData  []byte                 `protobuf:"bytes,3,opt,name=gradient_data,json=gradientData,proto3" json:"gradient_data,omitempty"` // compressed sparse gradient delta
	GradientHash  string                 `protobuf:"bytes,4,opt,name=gradient_hash,json=gradientHash,proto3" json:"gradient_hash,omitempty"` // SHA-256 of gradient_data
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                           // Ed25519 sig over (round_number + gradient_hash)
	S3Url         string                 `protobuf:"bytes,6,opt,name=s3_url,json=s3Url,proto3" json:"s3_url,omitempty"`                      // S3 object URL for gradient blob (key-only after validation)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradientUpdate) Reset() {
	*x = GradientUpdate{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradientUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradientUpdate) ProtoMessage() {}

func (x *GradientUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradientUpdate.ProtoReflect.Descriptor instead.
func (*GradientUpdate) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{17}
}

func (x *GradientUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GradientUpdate) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *GradientUpdate) GetGradientData() []byte {
	if x != nil {
		return x.GradientData
	}
	return nil
}

func (x *GradientUpdate) GetGradientHash() string {
	if x != nil {
		return x.GradientHash
	}
	return ""
}

func (x *GradientUpdate) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *GradientUpdate) GetS3Url() string {
	if x != nil {
		return x.S3Url
	}
	return ""
}

type GradientAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectionReason string                 `protobuf:"bytes,2,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	RewardSats      int64                  `protobuf:"varint,3,opt,name=reward_sats,json=rewardSats,proto3" json:"reward_sats,omitempty"` // 0 until round completes
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GradientAck) Reset() {
	*x = GradientAck{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradientAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradientAck) ProtoMessage() {}

func (x *GradientAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradientAck.ProtoReflect.Descriptor instead.
func (*GradientAck) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{18}
}

func (x *GradientAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *GradientAck) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *GradientAck) GetRewardSats() int64 {
	if x != nil {
		return x.RewardSats
	}
	return 0
}

var File_proto_coordinator_v1_coordinator_proto protoreflect.FileDescriptor

const file_proto_coordinator_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	"&proto/coordinator/v1/coordinator.proto\x12\x0ecoordinator.v1\"\xfb\x01\n" +
	"\x13RegisterNodeRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1e\n" +
	"\vln_node_uri\x18\x02 \x01(\tR\tlnNodeUri\x12D\n" +
	"\fcapabilities\x18\x03 \x01(\v2 .coordinator.v1.NodeCapabilitiesR\fcapabilities\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12#\n" +
	"\ronion_address\x18\x06 \x01(\tR\fonionAddress\"\xaf\x01\n" +
	"\x10NodeCapabilities\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\tR\x04tier\x12\x17\n" +
	"\avram_gb\x18\x02 \x01(\x02R\x06vramGb\x12\x15\n" +
	"\x06ram_gb\x18\x03 \x01(\x02R\x05ramGb\x12%\n" +
	"\x0ebandwidth_mbps\x18\x04 \x01(\x02R\rbandwidthMbps\x120\n" +
	"\x14supported_task_types\x18\x05 \x03(\tR\x12supportedTaskTypes\"\xbe\x01\n" +
	"\x14RegisterNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"stake_sats\x18\x04 \x01(\x03R\tstakeSats\x12\x1d\n" +
	"\n" +
	"bonus_mult\x18\x05 \x01(\x02R\tbonusMult\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\"\x9e\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x125\n" +
	"\ametrics\x18\x04 \x01(\v2\x1b.coordinator.v1.NodeMetricsR\ametrics\"\xa5\x01\n" +
	"\vNodeMetrics\x12.\n" +
	"\x13gpu_utilization_pct\x18\x01 \x01(\x02R\x11gpuUtilizationPct\x12 \n" +
	"\fvram_used_gb\x18\x02 \x01(\x02R\n" +
	"vramUsedGb\x12!\n" +
	"\factive_tasks\x18\x03 \x01(\x05R\vactiveTasks\x12!\n" +
	"\fuptime_hours\x18\x04 \x01(\x02R\vuptimeHours\"\x94\x01\n" +
	"\x11HeartbeatResponse\x12#\n" +
	"\rpending_tasks\x18\x01 \x01(\x05R\fpendingTasks\x12/\n" +
	"\x13coordinator_version\x18\x02 \x01(\tR\x12coordinatorVersion\x12)\n" +
	"\x10update_available\x18\x03 \x01(\bR\x0fupdateAvailable\"\x84\x01\n" +
	"\x15DeregisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"L\n" +
	"\x16DeregisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x81\x02\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12+\n" +
	"\x11encrypted_payload\x18\x03 \x01(\fR\x10encryptedPayload\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vreward_sats\x18\x05 \x01(\x03R\n" +
	"rewardSats\x12#\n" +
	"\rmodel_version\x18\x06 \x01(\tR\fmodelVersion\x12'\n" +
	"\x0fcoordinator_sig\x18\a \x01(\fR\x0ecoordinatorSig\"\xae\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\voutput_hash\x18\x03 \x01(\fR\n" +
	"outputHash\x12\x16\n" +
	"\x06output\x18\x04 \x01(\fR\x06output\x12\x17\n" +
	"\aexec_ms\x18\x05 \x01(\x03R\x06execMs\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"}\n" +
	"\rTaskResultAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12)\n" +
	"\x10rejection_reason\x18\x02 \x01(\tR\x0frejectionReason\x12%\n" +
	"\x0epayment_status\x18\x03 \x01(\tR\rpaymentStatus\"3\n" +
	"\x0fGetModelRequest\x12 \n" +
	"\fsub_model_id\x18\x01 \x01(\tR\n" +
	"subModelId\"\x8e\x04\n" +
	"\fModelVersion\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\tR\tversionId\x12!\n" +
	"\fround_number\x18\x02 \x01(\x05R\vroundNumber\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12Z\n" +
	"\x10sub_model_hashes\x18\x04 \x03(\v20.coordinator.v1.ModelVersion.SubModelHashesEntryR\x0esubModelHashes\x12T\n" +
	"\x0eots_proof_urls\x18\x05 \x03(\v2..coordinator.v1.ModelVersion.OtsProofUrlsEntryR\fotsProofUrls\x12\x1b\n" +
	"\tbtc_block\x18\x06 \x01(\x05R\bbtcBlock\x12!\n" +
	"\fots_verified\x18\a \x01(\bR\votsVerified\x12'\n" +
	"\x0fcoordinator_sig\x18\b \x01(\tR\x0ecoordinatorSig\x1aA\n" +
	"\x13SubModelHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11OtsProofUrlsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x11ListModelsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"d\n" +
	"\x12ListModelsResponse\x128\n" +
	"\bversions\x18\x01 \x03(\v2\x1c.coordinator.v1.ModelVersionR\bversions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"*\n" +
	"\x0fGetStakeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x86\x02\n" +
	"\vStakeStatus\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12#\n" +
	"\rcapacity_sats\x18\x02 \x01(\x03R\fcapacitySats\x12#\n" +
	"\rlocal_balance\x18\x03 \x01(\x03R\flocalBalance\x12!\n" +
	"\ftier_minimum\x18\x04 \x01(\x03R\vtierMinimum\x12)\n" +
	"\x10bonus_multiplier\x18\x05 \x01(\x02R\x0fbonusMultiplier\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12(\n" +
	"\x10last_verified_at\x18\a \x01(\x03R\x0elastVerifiedAt\"\xcb\x01\n" +
	"\x0eGradientUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fround_number\x18\x02 \x01(\x05R\vroundNumber\x12#\n" +
	"\rgradient_data\x18\x03 \x01(\fR\fgradientData\x12#\n" +
	"\rgradient_hash\x18\x04 \x01(\tR\fgradientHash\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x15\n" +
	"\x06s3_url\x18\x06 \x01(\tR\x05s3Url\"u\n" +
	"\vGradientAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12)\n" +
	"\x10rejection_reason\x18\x02 \x01(\tR\x0frejectionReason\x12\x1f\n" +
	"\vreward_sats\x18\x03 \x01(\x03R\n" +
	"rewardSats2\x87\x06\n" +
	"\x12CoordinatorService\x12Y\n" +
	"\fRegisterNode\x12#.coordinator.v1.RegisterNodeRequest\x1a$.coordinator.v1.RegisterNodeResponse\x12P\n" +
	"\tHeartbeat\x12 .coordinator.v1.HeartbeatRequest\x1a!.coordinator.v1.HeartbeatResponse\x12_\n" +
	"\x0eDeregisterNode\x12%.coordinator.v1.DeregisterNodeRequest\x1a&.coordinator.v1.DeregisterNodeResponse\x12G\n" +
	"\vStreamTasks\x12 .coordinator.v1.HeartbeatRequest\x1a\x14.coordinator.v1.Task0\x01\x12M\n" +
	"\x10SubmitTaskResult\x12\x1a.coordinator.v1.TaskResult\x1a\x1d.coordinator.v1.TaskResultAck\x12P\n" +
	"\x0fGetCurrentModel\x12\x1f.coordinator.v1.GetModelRequest\x1a\x1c.coordinator.v1.ModelVersion\x12Z\n" +
	"\x11ListModelVersions\x12!.coordinator.v1.ListModelsRequest\x1a\".coordinator.v1.ListModelsResponse\x12N\n" +
	"\x0eGetStakeStatus\x12\x1f.coordinator.v1.GetStakeRequest\x1a\x1b.coordinator.v1.StakeStatus\x12M\n" +
	"\x0eSubmitGradient\x12\x1e.coordinator.v1.GradientUpdate\x1a\x1b.coordinator.v1.GradientAckBJZHgithub.com/owmnetwork/owm-coordinator/proto/coordinator/v1;coordinatorv1b\x06proto3"

var (
	file_proto_coordinator_v1_coordinator_proto_rawDescOnce sync.Once
	file_proto_coordinator_v1_coordinator_proto_rawDescData []byte
)

func file_proto_coordinator_v1_coordinator_proto_rawDescGZIP() []byte {
	file_proto_coordinator_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_proto_coordinator_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coordinator_v1_coordinator_proto_rawDesc), len(file_proto_coordinator_v1_coordinator_proto_rawDesc)))
	})
	return file_proto_coordinator_v1_coordinator_proto_rawDescData
}

var file_proto_coordinator_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_coordinator_v1_coordinator_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),    // 0: coordinator.v1.RegisterNodeRequest
	(*NodeCapabilities)(nil),       // 1: coordinator.v1.NodeCapabilities
	(*RegisterNodeResponse)(nil),   // 2: coordinator.v1.RegisterNodeResponse
	(*HeartbeatRequest)(nil),       // 3: coordinator.v1.HeartbeatRequest
	(*NodeMetrics)(nil),            // 4: coordinator.v1.NodeMetrics
	(*HeartbeatResponse)(nil),      // 5: coordinator.v1.HeartbeatResponse
	(*DeregisterNodeRequest)(nil),  // 6: coordinator.v1.DeregisterNodeRequest
	(*DeregisterNodeResponse)(nil), // 7: coordinator.v1.DeregisterNodeResponse
	(*Task)(nil),                   // 8: coordinator.v1.Task
	(*TaskResult)(nil),             // 9: coordinator.v1.TaskResult
	(*TaskResultAck)(nil),          // 10: coordinator.v1.TaskResultAck
	(*GetModelRequest)(nil),        // 11: coordinator.v1.GetModelRequest
	(*ModelVersion)(nil),           // 12: coordinator.v1.ModelVersion
	(*ListModelsRequest)(nil),      // 13: coordinator.v1.ListModelsRequest
	(*ListModelsResponse)(nil),     // 14: coordinator.v1.ListModelsResponse
	(*GetStakeRequest)(nil),        // 15: coordinator.v1.GetStakeRequest
	(*StakeStatus)(nil),            // 16: coordinator.v1.StakeStatus
	(*GradientUpdate)(nil),         // 17: coordinator.v1.GradientUpdate
	(*GradientAck)(nil),            // 18: coordinator.v1.GradientAck
	nil,                            // 19: coordinator.v1.ModelVersion.SubModelHashesEntry
	nil,                            // 20: coordinator.v1.ModelVersion.OtsProofUrlsEntry
}
var file_proto_coordinator_v1_coordinator_proto_depIdxs = []int32{
	1,  // 0: coordinator.v1.RegisterNodeRequest.capabilities:type_name -> coordinator.v1.NodeCapabilities
	4,  // 1: coordinator.v1.HeartbeatRequest.metrics:type_name -> coordinator.v1.NodeMetrics
	19, // 2: coordinator.v1.ModelVersion.sub_model_hashes:type_name -> coordinator.v1.ModelVersion.SubModelHashesEntry
	20, // 3: coordinator.v1.ModelVersion.ots_proof_urls:type_name -> coordinator.v1.ModelVersion.OtsProofUrlsEntry
	12, // 4: coordinator.v1.ListModelsResponse.versions:type_name -> coordinator.v1.ModelVersion
	0,  // 5: coordinator.v1.CoordinatorService.RegisterNode:input_type -> coordinator.v1.RegisterNodeRequest
	3,  // 6: coordinator.v1.CoordinatorService.Heartbeat:input_type -> coordinator.v1.HeartbeatRequest
	6,  // 7: coordinator.v1.CoordinatorService.DeregisterNode:input_type -> coordinator.v1.DeregisterNodeRequest
	3,  // 8: coordinator.v1.CoordinatorService.StreamTasks:input_type -> coordinator.v1.HeartbeatRequest
	9,  // 9: coordinator.v1.CoordinatorService.SubmitTaskResult:input_type -> coordinator.v1.TaskResult
	11, // 10: coordinator.v1.CoordinatorService.GetCurrentModel:input_type -> coordinator.v1.GetModelRequest
	13, // 11: coordinator.v1.CoordinatorService.ListModelVersions:input_type -> coordinator.v1.ListModelsRequest
	15, // 12: coordinator.v1.CoordinatorService.GetStakeStatus:input_type -> coordinator.v1.GetStakeRequest
	17, // 13: coordinator.v1.CoordinatorService.SubmitGradient:input_type -> coordinator.v1.GradientUpdate
	2,  // 14: coordinator.v1.CoordinatorService.RegisterNode:output_type -> coordinator.v1.RegisterNodeResponse
	5,  // 15: coordinator.v1.CoordinatorService.Heartbeat:output_type -> coordinator.v1.HeartbeatResponse
	7,  // 16: coordinator.v1.CoordinatorService.DeregisterNode:output_type -> coordinator.v1.DeregisterNodeResponse
	8,  // 17: coordinator.v1.CoordinatorService.StreamTasks:output_type -> coordinator.v1.Task
	10, // 18: coordinator.v1.CoordinatorService.SubmitTaskResult:output_type -> coordinator.v1.TaskResultAck
	12, // 19: coordinator.v1.CoordinatorService.GetCurrentModel:output_type -> coordinator.v1.ModelVersion
	14, // 20: coordinator.v1.CoordinatorService.ListModelVersions:output_type -> coordinator.v1.ListModelsResponse
	16, // 21: coordinator.v1.CoordinatorService.GetStakeStatus:output_type -> coordinator.v1.StakeStatus
	18, // 22: coordinator.v1.CoordinatorService.SubmitGradient:output_type -> coordinator.v1.GradientAck
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_coordinator_v1_coordinator_proto_init() }
func file_proto_coordinator_v1_coordinator_proto_init() {
	if File_proto_coordinator_v1_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coordinator_v1_coordinator_proto_rawDesc), len(file_proto_coordinator_v1_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coordinator_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_proto_coordinator_v1_coordinator_proto_depIdxs,
		MessageInfos:      file_proto_coordinator_v1_coordinator_proto_msgTypes,
	}.Build()
	File_proto_coordinator_v1_coordinator_proto = out.File
	file_proto_coordinator_v1_coordinator_proto_goTypes = nil
	file_proto_coordinator_v1_coordinator_proto_depIdxs = nil
}
