apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
spec:
  template:
    spec:
      containers:
        - name: coordinator
          env:
            - name: OWM_SERVER_TLS_CERT_FILE
              value: /tls/grpc/tls.crt
            - name: OWM_SERVER_TLS_KEY_FILE
              value: /tls/grpc/tls.key
            - name: OWM_SERVER_CA_CERT_FILE
              value: /tls/grpc/ca.crt
          volumeMounts:
            - name: grpc-tls
              mountPath: /tls/grpc
              readOnly: true
      volumes:
        - name: grpc-tls
          secret:
            secretName: owm-coordinator-grpc-tls
